config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  scope :find_newest_article, -> { order(created_at: :desc).limit(5) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :given_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:family_name, :given_name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [ :show, :edit, :update, :destroy]

  def index
    @q = Post.order(created_at: :desc).ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(2)
    @new_posts = Post.find_newest_article
    @author = Author.first
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params) # ストロングパラメータを引数に
    @post.save # saveをしてデータベースに保存する。
    redirect_to @post
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params # ストロングパラメータを定義する
    params.require(:post).permit(:title, :body, :category)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mamatomo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">

        <!-- error -->
      <% if notice.present? %>
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= notice %></p>
        </div>
      <% end %>

      <% if alert.present? %>
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <p><%= alert %></p>
        </div>
      <% end %>
  <!-- //error -->

        <!--navbar-collapse -->
        <div class="collapse navbar-collapse" id="navbar-collapse-menu">
     <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
         <li><%= link_to "設定変更", edit_user_registration_path %></li>
         <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
       <% else %>
         <li><%= link_to "新規登録", new_user_registration_path %></li>
         <li><%= link_to "ログイン", new_user_session_path %></li>
       <% end %>
     </ul>
   </div><!-- /.navbar-collapse -->

<!--Retrieval-->
        <div class="col-md-12 retrieval">
         <div class="form-inline pull-right" style="margin-bottom:10px;">
           <form class="post_search" id="post_search" action="/posts" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
             <div class="form-group">
               <input placeholder="タイトルか本文を検索" class="form-control" type="search" name="q[title_or_body_cont]" id="q_title_or_body_cont">
               <input type="submit" name="commit" value="検索" class="btn btn-primary" data-disable-with="検索">
             </div>
</form>         </div>
        </div>
<!--//Retrieval-->

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header nav_logo">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- ★★★★下記の#を後ほど正しいURLに変更 -->
          <%= link_to "", root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <!-- ★★★★下記の#を後ほど正しいURLに変更 -->
            <li><a href="/posts/new">投稿する</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <!-- ★★★★下記の#を後ほど正しいURLに変更 -->
            <li><a href="#">最新</a></li>
            <li><a href="#">ランキング</a></li>
            <li><a href="#">妊娠・子育て</a></li>
            <li><a href="#">仕事・キャリア</a></li>
            <li><a href="#">お料理・レシピ</a></li>

          </ul>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-12">
  <h1>ブログ記事編集</h1>
  <%= form_with model: @post, local: true do |form| %>
    <div class="form-group">
      <%= form.label "タイトル" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label "カテゴリ" %>
      <%= form.text_field :category, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label "本文" %>
      <%= form.text_area :body, class: "form-control" %>
    </div>
    <%= form.submit '編集する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="row">
<!--left_side-->
  <div class="col-md-4 text-left">
    <div class="thumbnail">
      <img alt="著者イメージ" src="https://archive.fo/2BLPU/007b5291982bb1ef5b8b34ea9bb096a9a5028c12.jpeg" title="著者イメージ">
      <div class="caption text-center">
        <h3>sparta</h3>
        <p>hogehoge</p>
      </div>
    </div>
    <div class="list-group">
      <!-- 5件だけ記事を表示するように制御します -->
        <a class="list-group-item" href="/posts/7">てすと</a>
        <a class="list-group-item" href="/posts/6">なりなり</a>
        <a class="list-group-item" href="/posts/5">なるなる２</a>
        <a class="list-group-item" href="/posts/4">テスト</a>
        <a class="list-group-item" href="/posts/2">title</a>
    </div>
  </div>

<div class="col-md-8">
  <% @posts.each do |post| %>
    <div class="article">
      <h2>タイトル：<%= post.title %></h2>
      <p>カテゴリ：<%= post.category %></p>
      <p>作成日：<%= post.created_at %></p>
      <p><%= truncate(post.body, length: 50) %></p>
      <p><%= link_to "続きを読む", post, class: "btn btn-default" %></p>
    </div>
  <% end %>

</div>

</div>

app/views/posts/new.html.erb
<div class="col-md-12">
  <h1>つぶやき投稿</h1>
  <%= form_with model: @post, local: true do |form| %>
    <div class="form-group">
      <%= form.label "タイトル" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label "カテゴリ" %>
      <%= form.text_field :category, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label "本文" %>
      <%= form.text_area :body, class: "form-control" %>
    </div>
    <%= form.submit '登録する', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">
  <h1><%= @post.title %></h1>
  <p>カテゴリ: <%= @post.category %></p>
  <p>投稿日:<%= @post.created_at %></p>
  <hr>
  <p>
    <%= simple_format(@post.body) %>
  </p>
  <hr>
  <%= link_to "編集", edit_post_path(@post), class: "btn btn-default" %>
  <%= link_to "削除", post_path(@post), class: "btn btn-default", method: :delete %>
  <%= link_to "HOME", post_path, class: "btn btn-default" %>
</div>